server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: jyw123
    url: jdbc:mysql://175.178.108.114:3306/jyw?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
  application:
    name: jywdouble
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 175.178.108.114
    password: jyw123
    port: 6379