server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jyw
    password: Jyw123456
    url: jdbc:mysql://rm-2vc7307rxg3bfg4rhno.mysql.cn-chengdu.rds.aliyuncs.com:3306/jyw?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
  application:
    name: jywcommon
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848